name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Haskell
      uses: ./.github/actions/setup-haskell

    - name: Build dependencies
      run: cabal build all --only-dependencies --enable-tests

    - name: Build Project
      run: cabal build all --enable-tests

    - name: Install HLint
      run: cabal install hlint --overwrite-policy=always

    - name: Run HLint
      run: hlint .

    - name: Run Tests
      run: cabal test all
