name: Nuke All Artifacts
on: 
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            *
          failOnError: false
